### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Tresky** [jworley/gatsby-source-youtube#1]
Getting this error whenever I try to deploy my Gatsby build with this plugin installed.

```
error UNHANDLED EXCEPTION
5:54:47 PM: 
5:54:47 PM:   ReferenceError: regeneratorRuntime is not defined
5:54:47 PM:   
5:54:47 PM:   - normalize.js:45 
5:54:47 PM:     [repo]/[gatsby-source-youtube]/normalize.js:45:47
5:54:47 PM:   
5:54:47 PM:   - normalize.js:118 Object.<anonymous>
5:54:47 PM:     [repo]/[gatsby-source-youtube]/normalize.js:118:2
5:54:47 PM:   
5:54:47 PM:   - v8-compile-cache.js:178 Module._compile
5:54:47 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:178:30
5:54:47 PM:   
5:54:47 PM:   - v8-compile-cache.js:159 require
5:54:47 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
5:54:47 PM:   
5:54:47 PM:   - gatsby-node.js:9 Object.<anonymous>
5:54:47 PM:     [repo]/[gatsby-source-youtube]/gatsby-node.js:9:17
5:54:47 PM:   
5:54:47 PM:   - v8-compile-cache.js:178 Module._compile
5:54:47 PM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:178:30
```

Everything worked fine in my project until I swapped over to this plugin. I'm not sure exactly what the issue it, but it seems to be that the plugin is expecting `regeneratorRuntime` to be global, but it isn't.

Any thoughts on this?

**Comment by Tresky** [comment]
It looks like these two forks fixed the issue. Might consider merging one of these in.

@iyeraravind https://github.com/iyeraravind/gatsby-source-youtube
@manueljtejada https://github.com/manueljtejada/gatsby-source-youtube

**Comment by iyeraravind** [comment]
@Tresky I used this fix recently while migrating a site from Gatsby v1 to v2. Here's a pull request on a similar issue posted on gatsby-remark-relative-images - https://github.com/danielmahon/gatsby-remark-relative-images/pull/7 and here's a stackoverflow answer - https://stackoverflow.com/questions/28976748/regeneratorruntime-is-not-defined#34195553

Hope this helps.

**Comment by Tresky** [comment]
@iyeraravind Thanks a lot for the great response. 👍

**Comment by ghost** [comment]
@Tresky how were you able to fix using the babel polyfill? @jworley is this something you would consider merging?

**Comment by Tresky** [comment]
@jameygleason Hey Jamey. To fix this, I ended up switching to using the repo hosted by @iyeraravind. It works like a charm. I don't see any reason why he would delete his branch, but if you really want to host your own, you could fork this repo and then replicate the three commits that @iyeraravind made.

See here: https://github.com/iyeraravind/gatsby-source-youtube/commits/master

Edit: Or you could fork @iyeraravind's repo

**Comment by Tresky** [comment]
@iyeraravind Would you consider making a PR for your changes to merge back into this repo? I can imagine that more people will be running into this issue and since this is the repo listed on the Gatsby website, it would help avoid issues in the future (that is if the repo owner has notifications on and merges the PR).

**Comment by ljairath** [comment]
Yes, I am getting the same error. Could anyone tell clearly what's the best way to fix this.

**### error Plugin gatsby-source-youtube returned an error
  ReferenceError: regeneratorRuntime is not defined**

Thanks..

**Comment by ljairath** [comment]
Hi All

I tried the following it seems to not give me errors but I don't see allYoutubeVideo schema at all in the graphql???

**gatsby -v
2.4.8**

**Install:** Is it the right way to install?
**lj@2HV8RN2:~/vide$ npm install --save https://github.com/iyeraravind/gatsby-source-youtube**

npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-source-filesystem@1.5.39 requires a peer of gatsby@^1.9.250 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EACCES: permission denied, rename '/home/ljairath/vide/node_modules/.staging/fsevents-d9e10a70/node_modules/readable-stream' -> '/home/ljairath/vide/node_modules/.staging/readable-stream-611bfde0'

+ gatsby-source-youtube@1.0.1
updated 1 package and audited 27793 packages in 85.651s
found 0 vulnerabilities

**lj@CCS:~/vide$ gatsby develop**

success open and validate gatsby-configs — 0.006 s
success load plugins — 0.235 s
success onPreInit — 1.354 s
success delete html and css files from previous builds — 0.017 s
success initialize cache — 0.148 s
success copy gatsby files — 0.273 s
success onPreBootstrap — 0.007 s
⠂ source and transform nodesStarting to fetch data from Drupal
success source and transform nodes — 3.690 s
success building schema — 2.900 s
success createPages — 0.107 s
success createPagesStatefully — 0.056 s
success onPreExtractQueries — 0.016 s
success update schema — 0.306 s
success extract queries from components — 0.243 s
success run graphql queries — 0.152 s — 21/21 139.85 queries/second
success write out page data — 0.015 s
success write out redirect data — 0.004 s
⠄ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.164 s

info bootstrap finished - 14.163 s

 DONE  Compiled successfully in 12335ms

**Comment by ghost** [comment]
It looks like a fix is ready to be merged. @jworley can you confirm?

**Comment by davisc** [comment]
@ljairath your steps work for me. I'm also running 2.4.8

**Comment by adamrasheed** [comment]
Any updates on this? Did v2 break this plugin?

**Comment by mateodelnorte** [comment]
getting the same error. w/ latest gatsby and default starter. 
```
error Plugin gatsby-source-youtube returned an error
  ReferenceError: regeneratorRuntime is not defined
  - normalize.js:45
    [site]/[gatsby-source-youtube]/normalize.js:45:47
  - normalize.js:118 Object.<anonymous>
```

**Comment by ghost** [comment]
@mateodelnorte This is the maintainer's email. jason@jasonincode.com

God forbid something happened to the man, but he's been inactive for a year now.

Here's what I'm using instead.

`"https://github.com/iyeraravind/gatsby-source-youtube"`

Muting the thread. Hope this gets resolved.

**Comment by cedricdelpoux** [comment]
Hi everyone, this repository is outdated.

Please checkout the new version v2.0.0.
I'll do my best to maintain it actively.

Thank you very much
